CFLAGS = -Wall -Wfatal-errors -std=gnu++17 -I${CONDA_PREFIX}/include -I${CONDA_PREFIX}/include/cpp_h5_writer
CFLAGS = -Wall -Wfatal-errors -std=gnu++17 -I${CONDA_PREFIX}/include -I${CONDA_PREFIX}/include/cpp_h5_writer
